-- Baseline reconciliation migration.
--
-- This repo (impostergame.io, the web app) had NO supabase/migrations folder
-- at all before this change, even though the live Supabase project has been
-- running for a long time and is shared with the ImposterGame mobile app.
-- The original v2 / v2.2 / v2.3 migration files referenced in the mobile
-- app's brief were never committed anywhere and could not be recovered from
-- git history in either repo.
--
-- This file was generated by exporting the LIVE schema directly (function
-- definitions via pg_get_functiondef, columns via information_schema) on
-- 2026-07-26, rather than by replaying history. It documents what is
-- actually deployed today, so future migrations in this folder reason from
-- ground truth instead of a guess.
--
-- Every statement below is written to be idempotent (CREATE TABLE IF NOT
-- EXISTS / CREATE OR REPLACE FUNCTION) so this file is SAFE TO RUN AGAINST
-- THE LIVE DATABASE — it changes nothing that isn't already there. It is
-- also safe to run against a fresh staging Postgres to bootstrap one.
--
-- Known gap: the `updated_at` trigger on `rooms` that calls
-- set_rooms_updated_at() was not captured (pg_trigger wasn't queried), so it
-- is NOT recreated here to avoid a duplicate-trigger error against the live
-- DB. If standing this up on a fresh staging DB, add it manually:
--   create trigger <name> before update on public.rooms
--     for each row execute function public.set_rooms_updated_at();

-- ---------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------

create table if not exists public.rooms (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz
);

-- Empty leftover tables, same shape as `rooms`. Dropped in
-- 002_cleanup_empty_tables.sql — recreated here only so the baseline
-- accurately reflects pre-cleanup state.
create table if not exists public.rooms_backup (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz
);

create table if not exists public.rooms_duplicate_v2 (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz
);

-- ---------------------------------------------------------------------
-- 2. Functions (original / insecure-broadcast path — what the web app
--    currently calls). Left completely unmodified from what's live.
-- ---------------------------------------------------------------------

create or replace function public.set_rooms_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create or replace function public.toggle_player_ready(p_room_code text, p_player_id text)
returns jsonb
language plpgsql
as $function$
declare
  v_state jsonb;
  v_players jsonb;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if not exists (
    select 1 from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
    where p->>'id' = p_player_id
  ) then raise exception 'Player is not in this room'; end if;

  select jsonb_agg(
    case when p->>'id' = p_player_id
      then jsonb_set(p, '{ready}', to_jsonb(not coalesce((p->>'ready')::boolean, false)))
      else p
    end
  ) into v_players
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p;

  v_state := jsonb_set(v_state, '{players}', coalesce(v_players, '[]'::jsonb));
  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.cast_room_vote(p_room_code text, p_voter_id text, p_target_id text)
returns jsonb
language plpgsql
as $function$
declare
  v_state jsonb;
  v_votes jsonb;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if coalesce(v_state->>'stage', '') <> 'game' then raise exception 'Voting is not open'; end if;

  if not exists (
    select 1 from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
    where p->>'id' = p_voter_id
  ) then raise exception 'Voter is not in this room'; end if;

  if not exists (
    select 1 from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
    where p->>'id' = p_target_id
  ) then raise exception 'Vote target is not in this room'; end if;

  v_votes := coalesce(v_state->'votes', '{}'::jsonb) || jsonb_build_object(p_voter_id, p_target_id);
  v_state := jsonb_set(v_state, '{votes}', v_votes);
  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.restart_room_to_lobby(p_room_code text, p_host_id text)
returns jsonb
language plpgsql
as $function$
declare
  v_state jsonb;
  v_players jsonb;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if coalesce(v_state->>'hostPlayerId', '') <> p_host_id then raise exception 'Only the host can restart the room'; end if;

  select coalesce(jsonb_agg(
    (p - 'isImposter') || jsonb_build_object('ready', false)
  ), '[]'::jsonb) into v_players
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p;

  v_state := jsonb_set(v_state, '{stage}', '"lobby"'::jsonb);
  v_state := jsonb_set(v_state, '{players}', v_players);
  v_state := jsonb_set(v_state, '{round}', 'null'::jsonb);
  v_state := jsonb_set(v_state, '{turnIndex}', '0'::jsonb);
  v_state := jsonb_set(v_state, '{wordHistory}', '[]'::jsonb);
  v_state := jsonb_set(v_state, '{votes}', '{}'::jsonb);

  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.leave_room(p_room_code text, p_player_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_code text := upper(trim(p_room_code));
  v_state jsonb;
  v_players jsonb;
  v_votes jsonb := '{}'::jsonb;
  v_pair record;
  v_was_host boolean;
  v_leaving_name text;
  v_leaver_was_imposter boolean;
  v_stage text;
  v_new_host_id text;
  v_new_host_name text;
  v_len int;
  v_turn int;
begin
  select state into v_state
  from public.rooms
  where code = v_code
  for update;

  if v_state is null then
    return null;
  end if;

  select p->>'name', coalesce((p->>'isImposter')::boolean, false)
    into v_leaving_name, v_leaver_was_imposter
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
  where p->>'id' = p_player_id
  limit 1;

  if v_leaving_name is null then
    return v_state;
  end if;

  v_stage := coalesce(v_state->>'stage', 'lobby');
  v_was_host := coalesce(v_state->>'hostPlayerId', '') = p_player_id;

  select coalesce(jsonb_agg(p), '[]'::jsonb) into v_players
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
  where p->>'id' <> p_player_id;

  if jsonb_array_length(v_players) = 0 then
    delete from public.rooms where code = v_code;
    return null;
  end if;

  for v_pair in
    select key, value
    from jsonb_each_text(coalesce(v_state->'votes', '{}'::jsonb))
  loop
    if v_pair.key <> p_player_id and v_pair.value <> p_player_id then
      v_votes := v_votes || jsonb_build_object(v_pair.key, v_pair.value);
    end if;
  end loop;

  v_state := jsonb_set(v_state, '{players}', v_players);
  v_state := jsonb_set(v_state, '{votes}', v_votes);

  if v_leaver_was_imposter and v_stage = 'game' then
    v_state := jsonb_set(v_state, '{stage}', '"reveal"'::jsonb);
    v_state := jsonb_set(v_state, '{roundEndReason}', '"imposterLeft"'::jsonb);
    v_state := jsonb_set(
      v_state, '{roomNotice}',
      to_jsonb(v_leaving_name || ' (the imposter) left. Round over.')
    );
  else
    v_len := jsonb_array_length(v_players);
    v_turn := coalesce((v_state->>'turnIndex')::int, 0);
    if v_len > 0 then
      v_state := jsonb_set(v_state, '{turnIndex}', to_jsonb(v_turn % v_len));
    end if;
    v_state := jsonb_set(
      v_state, '{roomNotice}',
      to_jsonb(v_leaving_name || ' left the room.')
    );
  end if;

  if v_was_host then
    select p->>'id', p->>'name'
      into v_new_host_id, v_new_host_name
    from jsonb_array_elements(v_players) p
    limit 1;

    select coalesce(jsonb_agg(
      (p - 'isImposter') || jsonb_build_object('ready', false)
    ), '[]'::jsonb)
    into v_players
    from jsonb_array_elements(v_players) p;

    v_state := jsonb_set(v_state, '{hostPlayerId}', to_jsonb(v_new_host_id));
    v_state := jsonb_set(v_state, '{stage}', '"lobby"'::jsonb);
    v_state := jsonb_set(v_state, '{players}', v_players);
    v_state := jsonb_set(v_state, '{round}', 'null'::jsonb);
    v_state := jsonb_set(v_state, '{turnIndex}', '0'::jsonb);
    v_state := jsonb_set(v_state, '{wordHistory}', '[]'::jsonb);
    v_state := jsonb_set(v_state, '{votes}', '{}'::jsonb);
    v_state := v_state - 'roundEndReason';
    v_state := jsonb_set(
      v_state, '{roomNotice}',
      to_jsonb(v_leaving_name || ' left the room. ' || v_new_host_name || ' is now the host.')
    );
  end if;

  update public.rooms set state = v_state where code = v_code;
  return v_state;
end;
$function$;

create or replace function public.kick_room_player(p_room_code text, p_host_id text, p_player_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_state jsonb;
  v_players jsonb;
  v_votes jsonb;
  v_pair record;
  v_len int;
  v_turn int;
  v_kicked_imposter boolean;
  v_stage text;
  v_kicked_name text;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if coalesce(v_state->>'hostPlayerId', '') <> p_host_id then raise exception 'Only the host can remove players'; end if;
  if p_player_id = p_host_id then raise exception 'The host cannot remove themselves'; end if;

  v_stage := coalesce(v_state->>'stage', 'lobby');

  select p->>'name', coalesce((p->>'isImposter')::boolean, false)
    into v_kicked_name, v_kicked_imposter
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
  where p->>'id' = p_player_id
  limit 1;

  select coalesce(jsonb_agg(p), '[]'::jsonb) into v_players
  from jsonb_array_elements(coalesce(v_state->'players', '[]'::jsonb)) p
  where p->>'id' <> p_player_id;

  v_votes := '{}'::jsonb;
  for v_pair in select key, value from jsonb_each_text(coalesce(v_state->'votes', '{}'::jsonb))
  loop
    if v_pair.key <> p_player_id and v_pair.value <> p_player_id then
      v_votes := v_votes || jsonb_build_object(v_pair.key, v_pair.value);
    end if;
  end loop;

  v_state := jsonb_set(v_state, '{players}', v_players);
  v_state := jsonb_set(v_state, '{votes}', v_votes);

  if v_kicked_imposter and v_stage = 'game' then
    v_state := jsonb_set(v_state, '{stage}', '"reveal"'::jsonb);
    v_state := jsonb_set(v_state, '{roundEndReason}', '"imposterLeft"'::jsonb);
    v_state := jsonb_set(
      v_state, '{roomNotice}',
      to_jsonb(coalesce(v_kicked_name, 'The imposter') || ' (the imposter) was removed. Round over.')
    );
  else
    v_len := jsonb_array_length(v_players);
    v_turn := coalesce((v_state->>'turnIndex')::int, 0);
    if v_len > 0 then
      v_state := jsonb_set(v_state, '{turnIndex}', to_jsonb(v_turn % v_len));
    end if;
  end if;

  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.start_round(p_room_code text, p_host_id text, p_imposter_index integer, p_secret_word text, p_category_id text, p_starting_index integer, p_used_words jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_state jsonb;
  v_players jsonb;
  v_len int;
  v_imp int;
  v_start int;
  v_new_players jsonb := '[]'::jsonb;
  v_idx int := 0;
  v_p jsonb;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if coalesce(v_state->>'hostPlayerId', '') <> p_host_id then raise exception 'Only the host can start the round'; end if;

  v_players := coalesce(v_state->'players', '[]'::jsonb);
  v_len := jsonb_array_length(v_players);
  if v_len < 3 then raise exception 'Need at least 3 players to start'; end if;

  v_imp   := ((p_imposter_index % v_len) + v_len) % v_len;
  v_start := ((p_starting_index % v_len) + v_len) % v_len;

  for v_p in select value from jsonb_array_elements(v_players)
  loop
    v_new_players := v_new_players || jsonb_build_array(
      jsonb_set(v_p, '{isImposter}', to_jsonb(v_idx = v_imp))
    );
    v_idx := v_idx + 1;
  end loop;

  v_state := jsonb_set(v_state, '{players}', v_new_players);
  v_state := jsonb_set(v_state, '{stage}', '"game"'::jsonb);
  v_state := jsonb_set(v_state, '{round}',
    jsonb_build_object('categoryId', p_category_id, 'secretWord', p_secret_word));
  v_state := jsonb_set(v_state, '{turnIndex}', to_jsonb(v_start));
  v_state := jsonb_set(v_state, '{wordHistory}', '[]'::jsonb);
  v_state := jsonb_set(v_state, '{votes}', '{}'::jsonb);
  v_state := jsonb_set(v_state, '{usedWords}', coalesce(p_used_words, '[]'::jsonb));
  v_state := v_state - 'roundEndReason';

  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.submit_clue(p_room_code text, p_player_id text, p_word text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_state jsonb;
  v_players jsonb;
  v_len int;
  v_turn int;
  v_current_id text;
  v_current_name text;
  v_history jsonb;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then raise exception 'Room not found'; end if;
  if coalesce(v_state->>'stage', '') <> 'game' then raise exception 'The round is not active'; end if;

  v_players := coalesce(v_state->'players', '[]'::jsonb);
  v_len := jsonb_array_length(v_players);
  if v_len = 0 then raise exception 'No players in room'; end if;

  v_turn := coalesce((v_state->>'turnIndex')::int, 0) % v_len;
  v_current_id   := v_players->v_turn->>'id';
  v_current_name := v_players->v_turn->>'name';

  if v_current_id <> p_player_id then
    raise exception 'It is not your turn';
  end if;

  v_history := coalesce(v_state->'wordHistory', '[]'::jsonb)
    || jsonb_build_array(jsonb_build_object('name', v_current_name, 'word', p_word));

  v_state := jsonb_set(v_state, '{wordHistory}', v_history);
  v_state := jsonb_set(v_state, '{turnIndex}', to_jsonb((v_turn + 1) % v_len));

  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

create or replace function public.join_room(p_room_code text, p_player_id text, p_player_name text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_state jsonb;
  v_players jsonb;
  v_already boolean;
begin
  select state into v_state
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if v_state is null then
    raise exception 'Room not found';
  end if;

  v_players := coalesce(v_state->'players', '[]'::jsonb);

  v_already := exists (
    select 1 from jsonb_array_elements(v_players) p
    where p->>'id' = p_player_id
  );

  if not v_already and coalesce(v_state->>'stage', 'lobby') <> 'lobby' then
    raise exception 'This room is mid-round. Try again when they return to the lobby.';
  end if;

  if v_already then
    select jsonb_agg(
      case when p->>'id' = p_player_id
        then jsonb_set(p, '{name}', to_jsonb(coalesce(nullif(trim(p_player_name), ''), 'Player')))
        else p
      end
    ) into v_players
    from jsonb_array_elements(v_players) p;
  else
    v_players := v_players || jsonb_build_array(
      jsonb_build_object(
        'id', p_player_id,
        'name', coalesce(nullif(trim(p_player_name), ''), 'Player'),
        'ready', false
      )
    );
  end if;

  v_state := jsonb_set(v_state, '{players}', coalesce(v_players, '[]'::jsonb));
  update public.rooms set state = v_state where code = upper(trim(p_room_code));
  return v_state;
end;
$function$;

grant execute on function public.toggle_player_ready(text, text) to anon;
grant execute on function public.cast_room_vote(text, text, text) to anon;
grant execute on function public.restart_room_to_lobby(text, text) to anon;
grant execute on function public.leave_room(text, text) to anon;
grant execute on function public.kick_room_player(text, text, text) to anon;
grant execute on function public.start_round(text, text, int, text, text, int, jsonb) to anon;
grant execute on function public.submit_clue(text, text, text) to anon;
grant execute on function public.join_room(text, text, text) to anon;
